package com.smartfarming.ai.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.InputStream;

/**
 * Serves the Dashboard page's model-comparison table and feature importances.
 *
 * <p>These numbers are loaded verbatim from JSON files generated by the actual
 * Python training run (see {@code /ml/notebooks} and
 * {@code /ml/model-results}) — nothing here is hand-typed. If you retrain the
 * models, re-run the export scripts and these values update automatically on
 * next boot; there's no hardcoded accuracy anywhere in this class.
 */
@Service
public class DashboardService {

    private JsonNode cropModelComparison;
    private JsonNode cropFeatureImportance;
    private JsonNode fertilizerAttemptMetrics;

    @PostConstruct
    public void load() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        try (InputStream is = new ClassPathResource("datasets/crop_model_comparison.json").getInputStream()) {
            cropModelComparison = mapper.readTree(is);
        }
        try (InputStream is = new ClassPathResource("datasets/crop_feature_importance.json").getInputStream()) {
            cropFeatureImportance = mapper.readTree(is);
        }
        try (InputStream is = new ClassPathResource("datasets/fertilizer_model_metrics.json").getInputStream()) {
            fertilizerAttemptMetrics = mapper.readTree(is);
        }
    }

    public JsonNode getCropModelComparison() {
        return cropModelComparison;
    }

    public JsonNode getCropFeatureImportance() {
        return cropFeatureImportance;
    }

    /** The ~14% accuracy results from the (rejected) fertilizer ML attempt — shown transparently, not hidden. */
    public JsonNode getFertilizerAttemptMetrics() {
        return fertilizerAttemptMetrics;
    }
}
